config/routes.rb
Rails.application.routes.draw do
  resources :homes
  resources :posts
  # get 'articles/index'
  resources :tags
  resources :articles do 
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments
    has_many :taggings
    has_many :tags, through: :taggings

    def tag_list
        self.tags.collect do |tag|
            tag.name
        end.join(", ")
    end
    def tag_list=(tags_string)
        tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
        new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
        self.tags = new_or_found_tags
    end
    
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/post.rb
class Post < ApplicationRecord
    validates_presence_of :body
  
    after_create_commit { broadcast_prepend_to :posts }
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings 
    has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper 

  def index
    @articles = Article.all
  end

  def show 
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new 
  end

  def create
    @article = Article.create(article_params)
    if @article.save
      redirect_to article_path(@article), notice: "Article '#{@article.title}' Successfully Created!"
    else
       render 'new'
    end
  end 

  def edit 
    @article = Article.find(params[:id])
  end

  def update 
    @article = Article.find(params[:id])
    if @article.update(article_params)
      # flash.notice = "Article '#{@article.title}' Updated!"
      redirect_to article_path, notice: "Article '#{@article.title}' Updated!"
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path
  end

  # private 
  # def article_params
  #   params.require(:article).permit(:title, :body, :tag_list)
  # end 

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create 
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    def show 
        @comment = Article.find(params[:article_id]).comments.find(params[:id])
    end
    private 
    def comment_params
        params.require(:comment).permit(:author_name, :body)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @time = Time.now
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
    @post = Post.new

    # respond_to do |format|
    #   if @post.update(post_params)
    #     format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
    #     format.json { render :show, status: :ok, location: @post }
    #   else
    #     format.html { render :edit, status: :unprocessable_entity }
    #     format.json { render json: @post.errors, status: :unprocessable_entity }
    #   end
    # end
    
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    # @post = Post.find(params[:id])
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
  
    respond_to do |format|
      if @post.save
      format.html { redirect_to posts_path }
      format.json { render :show, status: :created, location: @post }
    else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@post, partial: 'posts/form', locals: { post: @post }) }
        format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @post.errors, status: :unprocessable_entity }
    end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    # @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@post, partial: 'posts/form', locals: { post: @post }) } 
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body, :likes)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def show
        @tag = Tag.find(params[:id])
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def article_params
        params.require(:article).permit(:title, :body, :tag_list)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: "Enter title" %><br>
    <%= f.label :body %>
    <%= f.text_area :body, placeholder: "Enter body" %>
  </div>
  <div>
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'form' %>
<%= link_to "Cancel", article_path %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<ul>
  <% @articles.each do |a| %>
    <li>👉 <%= link_to a.title, a %></li>
  <% end %>
</ul>
<%= link_to "New Article", new_article_path,class: "new_article" %>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form' %>
<%= link_to "Cancel", articles_path %>

app/views/articles/show.html.erb
<h1>Article</h1>
<div>
  <h3><%= @article.title %></h3>
  <p><%= @article.body %></p>
</div>
<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
<%= render 'comments/show' %>
<%= render 'comments/form' %>
<%= link_to "Edit", edit_article_path,class: "new_article" %>
<%= link_to "Delete", @article, method: :delete %>
<%= link_to "Back to Articles", articles_path %>

app/views/comments/_form.html.erb
<h2>Add a comment</h2>
<%= form_with model: [@article, @article.comments.build] do |f| %>
  <%= f.label :author_name %>
  <%= f.text_field :author_name, placeholder: "Your Name" %>
  <%= f.label :body %>
  <%= f.text_area :body, placeholder: "Enter Comment" %>
  <%= f.submit %>
<% end %>

app/views/comments/_show.html.erb
<h3>Comments (<%= @article.comments.size %>)</h3>
<% @article.comments.each do |comment| %>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
  <p><b>Commenter:</b>
    <%= comment.author_name %></p>
  <p><b>Comment:</b>
    <%= comment.body %></p>
<% end %>

app/views/homes/index.html.erb
<h1 data-turbo-frame>The current time is: <%= @time %></h1>
<%= turbo_frame_tag do %>
  <%= button_to "Refresh Time", root_path, method: :get, data: { turbo: "replace" } %>
<% end %>
<style>
  h1 {
  text-align: center;
  font-size: 2em;
  margin: 20px 0;
  }
  button {
  display: block;
  margin: 20px auto;
  padding: 10px 20px;
  font-size: 1.2em;
  border-radius: 5px;
  border: none;
  background-color: #00bcd4;
  color: white;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BloggerPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <p class="flash"><%= flash.notice %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :likes, style: "display: block" %>
    <%= form.number_field :likes %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div style="background: lightgrey; width: 300px; padding: 10px;">
  <%= turbo_frame_tag :post_form do %>
    <%= post.body %>
    <%= button_to "likes (#{post.likes || 1})", post_path(post, like: true), method: :put %>
    <br>
    <%#= render 'posts/form', post: @post %>
    <%= link_to :edit, edit_post_path(post) %>
  <% end %>
</div>
<br>

app/views/posts/edit.html.erb
<h1>Editing post</h1>
<%= turbo_frame_tag :post_form do %>
  <%= render "form", post: @post %>
<% end %>
<br>
<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<%= turbo_stream_from :posts %>
<%= turbo_frame_tag :post_form do %>
  <%= render 'posts/form', post: @post %>
<% end %>
<%= turbo_frame_tag :posts do %>
  <%= render @posts %>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= render "form", post: @post %>
<br>
<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>